runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: dist/aida-next/index.html
  upload: dist/aida-next/index.html
  expiration: 1s
- url: /
  static_dir: dist/aida-next